### ISSUE TITLE
Analyzer does not work after change of Website

### ISSUE THREAD

**Issue by crackytsi** [JesseBowling/CortexASNLookup#1]
The Service seems no longer to work exist:
https://shadowserver.org/wiki/pmwiki.php/Services/ipbgp
==> The page "Services/ipbgp" doesn't exist.

But this seems to work:
server:/opt/Cortex-Analyzers/analyzers/ASNLookup# whois -h asn.shadowserver.org origin 8.8.8.8
15169 | 8.8.8.0/24 | GOOGLE | US | Google LLC, US

I don't really know the reason, but the following error message appears when I try to run an analyzer:

{
  "errorMessage": "Error: Invalid output\nTraceback (most recent call last):\n  File \"./asnlookup.py\", line 70, in <module>\n    ASNLookup().run()\n  File \"./asnlookup.py\", line 56, in run\n    bgpip = self.search_bgpip(self.getData())\n  File \"./asnlookup.py\", line 39, in search_bgpip\n    ret = asnwhois.result[asnwhois.query[0]]._asdict()\n  File \"/usr/local/lib/python3.4/dist-packages/RashlyOutlaid/libwhois.py\", line 101, in get_result\n    self._perform_query()\n  File \"/usr/local/lib/python3.4/dist-packages/RashlyOutlaid/libwhois.py\", line 148, in _perform_query\n    self._query_multiple()\n  File \"/usr/local/lib/python3.4/dist-packages/RashlyOutlaid/libwhois.py\", line 176, in _query_multiple\n    self.read()\n  File \"/usr/local/lib/python3.4/dist-packages/RashlyOutlaid/libwhois.py\", line 82, in read\n    data = self._connection.recv(1024)\nConnectionResetError: [Errno 104] Connection reset by peer\n",
  "input": null,
  "success": false
}

**Comment by JesseBowling** [comment]
As I read this error, the important bit seems to be:

``ConnectionResetError: [Errno 104] Connection reset by peer\n"``

I believe something in your network path caused an issue. 

I just updated instructions (and bumped version number) after testing with Cortex 2. Please give another shot!

**Comment by crackytsi** [comment]
Thanks, sorry my fault, works now fine :)
